version: '3'

services:
  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - customer-service
    networks:
      - microservice-network

  # Product Service
  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - product-db
    environment:
      - MONGODB_URI=mongodb://product-db:27017/productdb
    networks:
      - microservice-network

  # Product Database
  product-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - product_data:/data/db
    networks:
      - microservice-network

  # Order Service
  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - order-db
    environment:
      - MONGODB_URI=mongodb://order-db:27017/orderdb
    networks:
      - microservice-network

  # Order Database
  order-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - order_data:/data/db
    networks:
      - microservice-network

  # Customer Service
  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    depends_on:
      - customer-db
    environment:
      - MONGODB_URI=mongodb://customer-db:27017/customerdb
    networks:
      - microservice-network

  # Customer Database
  customer-db:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - customer_data:/data/db
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  product_data:
  order_data:
  customer_data:
